/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.theks.exploration.init;

import net.theks.exploration.ExplorationMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

@EventBusSubscriber
public class ExplorationModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, ExplorationMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> DIDDY_BLUD_CT = REGISTRY.register("diddy_blud_ct",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.exploration.diddy_blud_ct")).icon(() -> new ItemStack(ExplorationModBlocks.LEAKING_WOOD_LOG.get())).displayItems((parameters, tabData) -> {
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_LOG.get().asItem());
				tabData.accept(ExplorationModBlocks.CLUSTERED_LEAKING_WOOD_LOG.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_LEAVES.get().asItem());
				tabData.accept(ExplorationModBlocks.STRIPPED_LEAKING_WOOD_LOG.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD.get().asItem());
				tabData.accept(ExplorationModBlocks.STRIPPED_LEAKING_WOOD_WOOD.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_PLANKS.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_STAIRS.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_SLAB.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_FENCE.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_FENCE_GATE.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_DOOR.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_TRAPDOOR.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_PRESSURE_PLATE.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_BUTTON.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_SIGN.get().asItem());
				tabData.accept(ExplorationModBlocks.LEAKING_WOOD_HANGING_SIGN.get().asItem());
				tabData.accept(ExplorationModItems.LEAKING_WOOD_BOAT.get());
				tabData.accept(ExplorationModItems.LEAKING_WOOD_CHEST_BOAT.get());
				tabData.accept(ExplorationModItems.RESIN_CLUSTER.get());
				tabData.accept(ExplorationModBlocks.RESIN_CLUSTER_BLOCK.get().asItem());
				tabData.accept(ExplorationModItems.RESIN_MUSH.get());
				tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BLOCK.get().asItem());
				tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_STAIRS.get().asItem());
				tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BRICKS.get().asItem());
				tabData.accept(ExplorationModBlocks.CHISELED_SMOOTH_RESIN_BRICKS.get().asItem());
				tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BRICK_WALL.get().asItem());
				tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BRICK_SLAB.get().asItem());
				tabData.accept(ExplorationModItems.CURED_RESIN_MUSH.get());
				tabData.accept(ExplorationModItems.RESIN_GLUE.get());
				tabData.accept(ExplorationModBlocks.SHALE.get().asItem());
				tabData.accept(ExplorationModBlocks.COBBLED_SHALE.get().asItem());
				tabData.accept(ExplorationModBlocks.COBBLED_SHALE_STAIRS.get().asItem());
				tabData.accept(ExplorationModBlocks.COBBLED_SHALE_SLAB.get().asItem());
				tabData.accept(ExplorationModBlocks.AMBER_ORE.get().asItem());
				tabData.accept(ExplorationModItems.AMBER.get());
				tabData.accept(ExplorationModBlocks.SHALE_IRON.get().asItem());
				tabData.accept(ExplorationModBlocks.SHALE_GOLD.get().asItem());
				tabData.accept(ExplorationModBlocks.SHALE_REDSTONE.get().asItem());
				tabData.accept(ExplorationModBlocks.SHALE_COAL.get().asItem());
				tabData.accept(ExplorationModItems.RESIN_DROPLET_SPAWN_EGG.get());
				tabData.accept(ExplorationModItems.AMBERLINED_PICKAXE.get());
				tabData.accept(ExplorationModItems.AMBERLINED_AXE.get());
				tabData.accept(ExplorationModItems.AMBERLINED_SWORD.get());
				tabData.accept(ExplorationModItems.AMBERLINED_SHOVEL.get());
				tabData.accept(ExplorationModItems.AMBERLINED_HOE.get());
				tabData.accept(ExplorationModBlocks.RESIN_MUSHROOM.get().asItem());
				tabData.accept(ExplorationModBlocks.SERPENTINITE.get().asItem());
				tabData.accept(ExplorationModBlocks.COBBLED_SERPENTINITE.get().asItem());
				tabData.accept(ExplorationModBlocks.NEPHRITE_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.POLISHED_SERPENTINITE.get().asItem());
				tabData.accept(ExplorationModItems.NEPHRITE.get());
				tabData.accept(ExplorationModItems.HUSH_PUPPY_SPAWN_EGG.get());
				tabData.accept(ExplorationModItems.THE_EXPLORATION.get());
				tabData.accept(ExplorationModItems.NEPHRITE_PICKAXE.get());
				tabData.accept(ExplorationModItems.NEPHRITE_BAR.get());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_BRICKS.get().asItem());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_BRICK_STAIRS.get().asItem());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_BRICKS_SLAB.get().asItem());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_PRESSURE_PLATE.get().asItem());
				tabData.accept(ExplorationModItems.NEPHRITE_AXE.get());
				tabData.accept(ExplorationModItems.NEPHRITE_SWORD.get());
				tabData.accept(ExplorationModItems.NEPHRITE_SHORT_SWORD.get());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_COAL_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_DIAMOND_ORE.get().asItem());
				tabData.accept(ExplorationModItems.NEPHRITE_SHOVEL.get());
				tabData.accept(ExplorationModItems.NEPHRITE_HOE.get());
				tabData.accept(ExplorationModItems.MAMA_SPIDER_SPAWN_EGG.get());
				tabData.accept(ExplorationModBlocks.GNEISS.get().asItem());
				tabData.accept(ExplorationModItems.RAW_HEMATITE.get());
				tabData.accept(ExplorationModBlocks.COBBLED_GNEISS.get().asItem());
				tabData.accept(ExplorationModBlocks.GNEISS_COAL_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.GNEISS_COPPER_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.GNEISS_IRON_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.SERPENTINITE_IRON_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.BLOCK_OF_NEPHRITE.get().asItem());
				tabData.accept(ExplorationModBlocks.GNEISS_LAPIS_LAZULI_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.GNEISS_GOLD_ORE.get().asItem());
				tabData.accept(ExplorationModBlocks.MOONITE_ORE.get().asItem());
				tabData.accept(ExplorationModItems.MOONITE.get());
				tabData.accept(ExplorationModItems.MOONITE_INGOT.get());
				tabData.accept(ExplorationModItems.HEMATITE_INGOT.get());
				tabData.accept(ExplorationModItems.HEMATITE_PICKAXE.get());
				tabData.accept(ExplorationModItems.HEMATITE_AXE.get());
				tabData.accept(ExplorationModItems.HEMATITE_SWORD.get());
				tabData.accept(ExplorationModItems.HEMATITE_SHOVEL.get());
				tabData.accept(ExplorationModItems.HEMATITE_HOE.get());
				tabData.accept(ExplorationModItems.CRYSTAL_SHARD.get());
				tabData.accept(ExplorationModBlocks.LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.BLUE_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.CYAN_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.GREEN_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.LIGHT_BLUE_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.LIME_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.MAGENTA_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.ORANGE_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.PINK_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.PURPLE_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.RED_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.YELLOW_LUMINANT_CRYSTAL.get().asItem());
				tabData.accept(ExplorationModBlocks.UMBRASTONE.get().asItem());
				tabData.accept(ExplorationModBlocks.CRYSTALIZED_UMBRASTONE.get().asItem());
				tabData.accept(ExplorationModBlocks.PULSATING_LAMP.get().asItem());
				tabData.accept(ExplorationModBlocks.UMBRASTONE_STAIRS.get().asItem());
				tabData.accept(ExplorationModBlocks.UMBRASTONE_SLAB.get().asItem());
				tabData.accept(ExplorationModBlocks.UNDEAD_DIRT.get().asItem());
				tabData.accept(ExplorationModItems.BONE_CLUB.get());
				tabData.accept(ExplorationModItems.JACKO_SPAWN_EGG.get());
				tabData.accept(ExplorationModItems.DEAD_MANS_SHOVEL.get());
				tabData.accept(ExplorationModItems.ENGRAVED_INGOT.get());
				tabData.accept(ExplorationModItems.NEPHRITE_HELMET.get());
				tabData.accept(ExplorationModItems.NEPHRITE_CHESTPLATE.get());
				tabData.accept(ExplorationModItems.NEPHRITE_LEGGINGS.get());
				tabData.accept(ExplorationModItems.NEPHRITE_BOOTS.get());
				tabData.accept(ExplorationModItems.HEMATITE_HELMET.get());
				tabData.accept(ExplorationModItems.HEMATITE_CHESTPLATE.get());
				tabData.accept(ExplorationModItems.HEMATITE_LEGGINGS.get());
				tabData.accept(ExplorationModItems.HEMATITE_BOOTS.get());
				tabData.accept(ExplorationModItems.STICKY_AMBERLINED_BOOTS.get());
				tabData.accept(ExplorationModItems.MOONITE_HELMET.get());
				tabData.accept(ExplorationModItems.MOONITE_CHESTPLATE.get());
				tabData.accept(ExplorationModItems.MOONITE_LEGGINGS.get());
				tabData.accept(ExplorationModItems.MOONITE_BOOTS.get());
				tabData.accept(ExplorationModItems.AMBERLINED_HELMET.get());
				tabData.accept(ExplorationModItems.AMBERLINED_CHESTPLATE.get());
				tabData.accept(ExplorationModItems.AMBERLINED_LEGGINGS.get());
				tabData.accept(ExplorationModItems.AMBERLINED_BOOTS.get());
				tabData.accept(ExplorationModItems.ENGRAVED_HELMET.get());
				tabData.accept(ExplorationModItems.ENGRAVED_CHESTPLATE.get());
				tabData.accept(ExplorationModItems.ENGRAVED_LEGGINGS.get());
				tabData.accept(ExplorationModItems.ENGRAVED_BOOTS.get());
				tabData.accept(ExplorationModBlocks.ENGRAVED_STONE_BRICKS.get().asItem());
				tabData.accept(ExplorationModItems.DEAD_MANS_SICKLE.get());
			}).withSearchBar().build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.NATURAL_BLOCKS) {
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_LOG.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_LEAVES.get().asItem());
			tabData.accept(ExplorationModBlocks.CLUSTERED_LEAKING_WOOD_LOG.get().asItem());
			tabData.accept(ExplorationModBlocks.SHALE.get().asItem());
			tabData.accept(ExplorationModBlocks.COBBLED_SHALE.get().asItem());
			tabData.accept(ExplorationModBlocks.AMBER_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.SHALE_IRON.get().asItem());
			tabData.accept(ExplorationModBlocks.SHALE_GOLD.get().asItem());
			tabData.accept(ExplorationModBlocks.SHALE_REDSTONE.get().asItem());
			tabData.accept(ExplorationModBlocks.SHALE_COAL.get().asItem());
			tabData.accept(ExplorationModBlocks.RESIN_MUSHROOM.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE.get().asItem());
			tabData.accept(ExplorationModBlocks.COBBLED_SERPENTINITE.get().asItem());
			tabData.accept(ExplorationModBlocks.NEPHRITE_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.POLISHED_SERPENTINITE.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_LEAVES.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE_COAL_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE_DIAMOND_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.GNEISS.get().asItem());
			tabData.accept(ExplorationModBlocks.COBBLED_GNEISS.get().asItem());
			tabData.accept(ExplorationModBlocks.GNEISS_COAL_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.GNEISS_COPPER_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.GNEISS_IRON_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE_IRON_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.GNEISS_LAPIS_LAZULI_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.GNEISS_GOLD_ORE.get().asItem());
			tabData.accept(ExplorationModBlocks.UMBRASTONE.get().asItem());
			tabData.accept(ExplorationModBlocks.CRYSTALIZED_UMBRASTONE.get().asItem());
			tabData.accept(ExplorationModBlocks.UNDEAD_DIRT.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
			tabData.accept(ExplorationModBlocks.STRIPPED_LEAKING_WOOD_LOG.get().asItem());
			tabData.accept(ExplorationModBlocks.STRIPPED_LEAKING_WOOD_WOOD.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_PLANKS.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_STAIRS.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_SLAB.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_FENCE.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_FENCE_GATE.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_DOOR.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_TRAPDOOR.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_PRESSURE_PLATE.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_BUTTON.get().asItem());
			tabData.accept(ExplorationModBlocks.RESIN_CLUSTER_BLOCK.get().asItem());
			tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BLOCK.get().asItem());
			tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_STAIRS.get().asItem());
			tabData.accept(ExplorationModBlocks.COBBLED_SHALE_STAIRS.get().asItem());
			tabData.accept(ExplorationModBlocks.COBBLED_SHALE_SLAB.get().asItem());
			tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BRICKS.get().asItem());
			tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BRICK_SLAB.get().asItem());
			tabData.accept(ExplorationModBlocks.CHISELED_SMOOTH_RESIN_BRICKS.get().asItem());
			tabData.accept(ExplorationModBlocks.SMOOTH_RESIN_BRICK_WALL.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_LOG.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_WOOD.get().asItem());
			tabData.accept(ExplorationModBlocks.STRIPPED_FROZEN_LOG.get().asItem());
			tabData.accept(ExplorationModBlocks.STRIPPED_FROZEN_WOOD.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_PLANKS.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_STAIRS.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_SLAB.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_FENCE.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_FENCE_GATE.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_DOOR.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_TRAPDOOR.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_PRESSURE_PLATE.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_BUTTON.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE_BRICKS.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE_BRICK_STAIRS.get().asItem());
			tabData.accept(ExplorationModBlocks.SERPENTINITE_BRICKS_SLAB.get().asItem());
			tabData.accept(ExplorationModBlocks.BLOCK_OF_NEPHRITE.get().asItem());
			tabData.accept(ExplorationModBlocks.LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.BLUE_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.CYAN_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.GREEN_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.LIGHT_BLUE_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.LIME_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.MAGENTA_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.ORANGE_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.PINK_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.PURPLE_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.RED_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.YELLOW_LUMINANT_CRYSTAL.get().asItem());
			tabData.accept(ExplorationModBlocks.UMBRASTONE.get().asItem());
			tabData.accept(ExplorationModBlocks.CRYSTALIZED_UMBRASTONE.get().asItem());
			tabData.accept(ExplorationModBlocks.PULSATING_LAMP.get().asItem());
			tabData.accept(ExplorationModBlocks.UMBRASTONE_STAIRS.get().asItem());
			tabData.accept(ExplorationModBlocks.UMBRASTONE_SLAB.get().asItem());
			tabData.accept(ExplorationModBlocks.ENGRAVED_STONE_BRICKS.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_SIGN.get().asItem());
			tabData.accept(ExplorationModBlocks.LEAKING_WOOD_HANGING_SIGN.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_SIGN.get().asItem());
			tabData.accept(ExplorationModBlocks.FROZEN_HANGING_SIGN.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
			tabData.accept(ExplorationModItems.LEAKING_WOOD_BOAT.get());
			tabData.accept(ExplorationModItems.LEAKING_WOOD_CHEST_BOAT.get());
			tabData.accept(ExplorationModItems.AMBERLINED_PICKAXE.get());
			tabData.accept(ExplorationModItems.AMBERLINED_AXE.get());
			tabData.accept(ExplorationModItems.AMBERLINED_SHOVEL.get());
			tabData.accept(ExplorationModItems.AMBERLINED_HOE.get());
			tabData.accept(ExplorationModItems.THE_EXPLORATION.get());
			tabData.accept(ExplorationModItems.FROZEN_BOAT.get());
			tabData.accept(ExplorationModItems.FROZEN_CHEST_BOAT.get());
			tabData.accept(ExplorationModItems.NEPHRITE_PICKAXE.get());
			tabData.accept(ExplorationModItems.NEPHRITE_AXE.get());
			tabData.accept(ExplorationModItems.NEPHRITE_SWORD.get());
			tabData.accept(ExplorationModItems.NEPHRITE_SHORT_SWORD.get());
			tabData.accept(ExplorationModItems.NEPHRITE_SHOVEL.get());
			tabData.accept(ExplorationModItems.NEPHRITE_HOE.get());
			tabData.accept(ExplorationModItems.HEMATITE_PICKAXE.get());
			tabData.accept(ExplorationModItems.HEMATITE_AXE.get());
			tabData.accept(ExplorationModItems.HEMATITE_SHOVEL.get());
			tabData.accept(ExplorationModItems.HEMATITE_HOE.get());
			tabData.accept(ExplorationModItems.DEAD_MANS_SHOVEL.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
			tabData.accept(ExplorationModItems.RESIN_DROPLET_SPAWN_EGG.get());
			tabData.accept(ExplorationModItems.HUSH_PUPPY_SPAWN_EGG.get());
			tabData.accept(ExplorationModItems.BOUND_SOUL_SPAWN_EGG.get());
			tabData.accept(ExplorationModItems.MAMA_SPIDER_SPAWN_EGG.get());
			tabData.accept(ExplorationModItems.CRYSTALIZED_ZOMBIE_SPAWN_EGG.get());
			tabData.accept(ExplorationModItems.JACKO_SPAWN_EGG.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.INGREDIENTS) {
			tabData.accept(ExplorationModItems.AMBER.get());
			tabData.accept(ExplorationModItems.RESIN_GLUE.get());
			tabData.accept(ExplorationModItems.NEPHRITE.get());
			tabData.accept(ExplorationModItems.NEPHRITE_BAR.get());
			tabData.accept(ExplorationModItems.RAW_HEMATITE.get());
			tabData.accept(ExplorationModItems.MOONITE.get());
			tabData.accept(ExplorationModItems.HEMATITE_INGOT.get());
			tabData.accept(ExplorationModItems.CRYSTAL_SHARD.get());
			tabData.accept(ExplorationModItems.ENGRAVED_INGOT.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.REDSTONE_BLOCKS) {
			tabData.accept(ExplorationModBlocks.SERPENTINITE_PRESSURE_PLATE.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.COMBAT) {
			tabData.accept(ExplorationModItems.AMBERLINED_SWORD.get());
			tabData.accept(ExplorationModItems.HEMATITE_SWORD.get());
			tabData.accept(ExplorationModItems.BONE_CLUB.get());
			tabData.accept(ExplorationModItems.NEPHRITE_HELMET.get());
			tabData.accept(ExplorationModItems.NEPHRITE_CHESTPLATE.get());
			tabData.accept(ExplorationModItems.NEPHRITE_LEGGINGS.get());
			tabData.accept(ExplorationModItems.NEPHRITE_BOOTS.get());
			tabData.accept(ExplorationModItems.HEMATITE_HELMET.get());
			tabData.accept(ExplorationModItems.HEMATITE_CHESTPLATE.get());
			tabData.accept(ExplorationModItems.HEMATITE_LEGGINGS.get());
			tabData.accept(ExplorationModItems.HEMATITE_BOOTS.get());
			tabData.accept(ExplorationModItems.STICKY_AMBERLINED_BOOTS.get());
			tabData.accept(ExplorationModItems.AMBERLINED_HELMET.get());
			tabData.accept(ExplorationModItems.AMBERLINED_CHESTPLATE.get());
			tabData.accept(ExplorationModItems.AMBERLINED_LEGGINGS.get());
			tabData.accept(ExplorationModItems.AMBERLINED_BOOTS.get());
			tabData.accept(ExplorationModItems.ENGRAVED_HELMET.get());
			tabData.accept(ExplorationModItems.ENGRAVED_CHESTPLATE.get());
			tabData.accept(ExplorationModItems.ENGRAVED_LEGGINGS.get());
			tabData.accept(ExplorationModItems.ENGRAVED_BOOTS.get());
			tabData.accept(ExplorationModItems.DEAD_MANS_SICKLE.get());
		}
	}
}